version: "3.9"

services:
  app:
    image: cosmtrek/air
    environment:
      - DB_HOST=db
      - DB_USER=mysql
      - DB_PASSWORD=mysql
      - DB_NAME=callkaiwaibbs
    working_dir: /app
    ports:
      - 8080:8080
    networks:
      - app
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=callkaiwaibbs
    networks:
      - app
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=mysql
      - PMA_PASSWORD=mysql
    networks:
      - phpmyadmin
    depends_on:
      - db

networks:
  app:
  phpmyadmin:
