// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IPAddressLog is the predicate function for ipaddresslog builders.
type IPAddressLog func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
