// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IPAddressLogsColumns holds the columns for the "ip_address_logs" table.
	IPAddressLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip_address", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "post_ip_address_log", Type: field.TypeInt},
	}
	// IPAddressLogsTable holds the schema information for the "ip_address_logs" table.
	IPAddressLogsTable = &schema.Table{
		Name:       "ip_address_logs",
		Columns:    IPAddressLogsColumns,
		PrimaryKey: []*schema.Column{IPAddressLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ip_address_logs_posts_ip_address_log",
				Columns:    []*schema.Column{IPAddressLogsColumns[4]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "gender", Type: field.TypeInt},
		{Name: "introduction", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "tweet_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "tiktok_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "contact_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "contact_id", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IPAddressLogsTable,
		PostsTable,
	}
)

func init() {
	IPAddressLogsTable.ForeignKeys[0].RefTable = PostsTable
}
